version: '3.7'

services:

  backend1:
    build:
      context: ./apps/nest
      dockerfile: first.Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3000
  backend2:
    build:
      context: ./apps/nest
      dockerfile: second.Dockerfile
    restart: unless-stopped
    ports:
      - 3002:3000

  frontend:
    build:
      context: ./apps/react
    ports:
      - 4200:4200
