version: '3.7'

services:

  backend:
    build:
      context: ./
      dockerfile: ./apps/nest/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
  proxy1:
    build:
      context: ./
      dockerfile: ./apps/nest/first.Dockerfile
    restart: unless-stopped
    ports:
      - 3001:80
  proxy2:
    build:
      context: ./
      dockerfile: ./apps/nest/second.Dockerfile
    restart: unless-stopped
    ports:
      - 3002:80

  frontend:
    build:
      context: ./
      dockerfile: ./apps/react/Dockerfile
    ports:
      - 4200:80
